Upgrade buildpacks so we can deploy on Heroku
We see the following errors when trying to deploy:

```
-----> Building on the Heroku-22 stack
-----> Using buildpacks:
       1. https://github.com/elixir-buildpack/heroku-buildpack.git
       2. https://github.com/gjaldon/heroku-buildpack-phoenix-static.git
       3. https://github.com/ianpurvis/heroku-buildpack-version
-----> Elixir app detected
-----> Will export the following config vars:
CANONICAL_HOST
DATABASE_URL
INITIAL_USER_EMAIL
LANG
LIVE_VIEW_SIGNING_SALT
MIX_ENV
POOL_SIZE
SECRET_KEY_BASE
SOURCE_VERSION
       * MIX_ENV=prod
-----> Checking Erlang and Elixir versions
       Will use the following versions:
       * Stack heroku-22
       * Erlang 25.3.1
       * Elixir v1.14.5
ERROR: the current stack is not supported, upgrade your stack to continue
 !     Push rejected, failed to compile Elixir app.
 !     Push failed
```